import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'
    className={`${inter.className} h-full scroll-smooth antialiased`}>
      <body className="flex min-h-full flex-col bg-blue-50">
      <Navbar />
        <main className='grow'>         
        {children}        
        </main>
        <Footer />
      </body>
    </html>
  )
}
